### ISSUE TITLE
Indigo release

### ISSUE THREAD

**Issue by anqixu** [ros-drivers/gscam#17]
Please consider releasing indigo debs. I can confirm that it compiles and runs just fine on 14.04 x64.

**Comment by k-okada** [comment]
any update?

**Comment by GhostFlying** [comment]
+1

**Comment by cesare-montresor** [comment]
+1

**Comment by mihaibujanca** [comment]
+1

**Comment by trapi789** [comment]
+1

**Comment by longjie** [comment]
+1

**Comment by 130s** [comment]
Ping @jbohren

**Comment by joshvillbrandt** [comment]
Would also like a jade release please! This was the only camera driver that worked out-of-the-box for my particular setup.

**Comment by wynn4** [comment]
+1

**Comment by k-okada** [comment]
@dirk-thomas thank you ! https://github.com/ros/rosdistro/pull/15214
