### ISSUE TITLE
assertion failed: (outpad)

### ISSUE THREAD

**Issue by MaMadDl** [ros-drivers/gscam#30]
Hi 
im getting following error when running gscam to connect to a gstreamer sender with this config:
<env name="GSCAM_CONFIG" value="udpsrc port=9000 caps=application/x-rtp, media=(string)video, clrate=(int)90000, encoding-name=(string)H264 ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink  sync=false"/>

ERROR:/home/mamaddl/catkin_ws/src/gscam/src/gscam.cpp:150:bool gscam::GSCam::init_stream(): assertion failed: (outpad)
[gscam-3] process has died [pid 10794, exit code -6, cmd /home/mamaddl/catkin_ws/devel/lib/gscam/gscam /gscam/camera_info:=/camera/camera_info /gscam/image_raw:=/camera/image_raw /gscam/set_camera_info:=/camera/set_camera_info __name:=gscam __log:=/home/mamaddl/.ros/log/08193ad4-51aa-11e6-b8ae-74d02bbe85f6/gscam-3.log].
log file: /home/mamaddl/.ros/log/08193ad4-51aa-11e6-b8ae-74d02bbe85f6/gscam-3*.log

thanks in advance!

**Comment by aishwaryyasarkar** [comment]
Did you find a solution to this?

**Comment by MaMadDl** [comment]
The Error Was In My Pipeline Which Couldn't Be Processed In Gscam

**Comment by aishwaryyasarkar** [comment]
Hi! thanks for replying. I am a beginner in all of this and have never worked with ros before. Could you please tell me in details how to fix the pipeline?

**Comment by MaMadDl** [comment]
It's Not ROS based Error But Rather Gstreamer Error 
Make Sure You Don't Have Output at the end of your Pipeline(like udpsink or etc)
This Is An Example Gscam that Opens camera located at video1
` <env name="GSCAM_CONFIG" value="v4l2src device=/dev/video1 ! ffmpegcolorspace " />`
and also make sure You are using plugins from the same version (don't mix 0.1 and 1.0 together)

**Comment by aishwaryyasarkar** [comment]
Thanks, I'll try it. Also, which camera did you use?

*With Regards,*
*Aishwarya Sarkar*

**Comment by MaMadDl** [comment]
My set up was rather complex due to my use-case 
It Was Not A camera. It Was a Stream I got From Wireless Network Which i used to redirect to An ```/dev/video``` But The Original Image Came From a Rasicam On A RaspberryPi3.

**Comment by MaMadDl** [comment]
My set up was rather complex due to my use-case 
It Was Not A camera. It Was a Stream I got From Wireless Network Which i used to redirect to An ```/dev/video``` But The Original Image Came From a Rasicam On A RaspberryPi3.
