### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by clydemcqueen** [ros-drivers/gscam#56]
Any plans to support ROS2? (Or any forks that support ROS2?)

**Comment by clydemcqueen** [comment]
I created a ROS2 port here: https://github.com/clydemcqueen/gscam2

If there's interest I could clean this up and release it for Dashing, Eloquent and Foxy.

**Comment by k-okada** [comment]
Ok, I have created https://github.com/ros-drivers/gscam/tree/ros2 branch,
so please send PR against this.

--
◉ Kei Okada



2020年8月25日(火) 7:23 Clyde McQueen <notifications@github.com>:

**Comment by clydemcqueen** [comment]
https://github.com/ros-drivers/gscam/pull/66

**Comment by clydemcqueen** [comment]
I have updated the PR to run on Foxy, Galactic and Rolling.

I will track the Rolling migration to Jammy and test the PR on GStreamer 1.18 in the coming weeks.

I am willing to be a gscam maintainer for both ROS1 and ROS2.

Thanks.

**Comment by clydemcqueen** [comment]
Jammy + gstreamer 1.20 + gscam passed tests on the buildfarm. :-) https://build.ros2.org/view/Rdev/job/Rdev__gscam__ubuntu_jammy_amd64/

I will close this issue when releases are complete on Foxy, Galactic and Rolling.

**Comment by clydemcqueen** [comment]
gscam is now released for Foxy, Galactic and Rolling (on Jammy). Closing.
