### ISSUE TITLE
Attempt to stream from rtsp

### ISSUE THREAD

**Issue by HHendy69** [ros-drivers/gscam#73]
I am trying to stream a video from gimble camera but I getting:

[FATAL] [1626774208.110004686]: Invalid 'video_stream_provider': rtsp://192.168.0.201:554/live

in the launch file I changed to param name="gscam_config" value="gst-launch-1.0 -v rtspsrc location=rtsp://192.168.0.201:554/live0 drop-on-latency=true use-pipeline-clock=true do-retransmission=false latency=0 protocols=GST_RTSP_LOWER_TRANS_UDP ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink sync=true

Do I miss anything else?

**Comment by clydemcqueen** [comment]
I assume that `gst-launch-1.0 -v rtspsrc location=rtsp://192.168.0.201:554/live0 drop-on-latency=true use-pipeline-clock=true do-retransmission=false latency=0 protocols=GST_RTSP_LOWER_TRANS_UDP ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink sync=true` works. If it doesn't, fix that first.

Then remove the initial `gst-launch-1.0` and the trailing `autovideosink sync=true` and set gscam_config to the shortened string.

You may need to add a `videoconvert` element to the end.

The final gscam_config string might look like this: `rtspsrc location=rtsp://192.168.0.201:554/live0 drop-on-latency=true use-pipeline-clock=true do-retransmission=false latency=0 protocols=GST_RTSP_LOWER_TRANS_UDP ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert`

**Comment by HHendy69** [comment]
That worked fine and with the videoconvert argument I got it on the image on a topic

I am closing the issue 

Thank you very much
