### ISSUE TITLE
GStreamer-CRITICAL issue [ gst_buffer_resize_range: assertion 'gst_buffer_is_writable (buffer)' failed ]

### ISSUE THREAD

**Issue by KangHyunwoogi** [ros-drivers/gscam#92]
(gscam:17521): GStreamer-CRITICAL **: 01:39:03.281: gst_buffer_resize_range: assertion 'gst_buffer_is_writable (buffer)' failed

(gscam:17521): GStreamer-WARNING **: 01:39:03.282: free_priv_data: object finalizing but still has parent (object:0xaaab2459a7e0, parent:0xaaab2456b6b0)

(gscam:17521): GStreamer-WARNING **: 01:39:03.282: free_priv_data: object finalizing but still has 1 parents (object:0xaaab2459a7e0)

Anyone who solve this problem??

**Comment by Grimwork** [comment]
Same problem here, did you solve it ?

**Comment by KangHyunwoogi** [comment]
> Same problem here, did you solve it ?

It because of gstreamer version issue.
You can run your code with modifying code with link as below! 
https://github.com/ros-drivers/gscam/pull/61

**Comment by Grimwork** [comment]
Thanks for the quick answer !
I have found another solution that work too here #82.
